#!/usr/bin/python
# makeblog - A simple offline Blog.
# Copyright (C) 2013 Stefan J. Betz <info@stefan-betz.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from makeblog.tools import options
from makeblog.blog import Blog
from os import access, F_OK, makedirs, chdir
from os.path import exists
from http.server import SimpleHTTPRequestHandler
from socketserver import TCPServer
import json

if options.title:
    b = Blog()
    b.newpost(options.title)
elif options.build:
    b = Blog()
    b.build()
elif options.serve:
    print("Starting Webserver for http://127.0.0.1:8000/")
    chdir('dst/')
    httpd = TCPServer(('127.0.0.1',8000), SimpleHTTPRequestHandler)
    httpd.serve_forever()
elif options.init:
    for directory in ('src','posts','drafts'):
        if not exists(directory):
            makedirs(directory)
    config = {
        'blog':{
            'name':'''My's Blog''',
            'url':'http://blog.domain.tld',
            'description':'Because i can!',
            'googleplus':True,
            'twitter':True,
            'categories':['category1', 'category2', 'category4' ],
            'defaultauthor':'me',
            'timezone':'Europe/Berlin',
            'dateformat':'%Y/%m/%d %H:%M:%S'
        },
        'authors':{
            'me':{
                'name':'Full Name',
                'nick':'nickname',
                'googleplus':'http...',
                'twitter':'http...',
                'amazon':None,
                'bitcoin':None,
                'mail':'info@domain.tld'
            }
        }
    }
    if not access('config.json', F_OK):
        with open('config.json','w') as f:
            json.dump(config,f,indent=1,ensure_ascii=False)
        print("You should edit config.json.")
