#!/usr/bin/python
# makeblog - A simple offline Blog.
# Copyright (C) 2013-2018 Stefan J. Betz <info@stefan-betz.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from makeblog.tools import options, parse_args
from makeblog.blog import Blog
from makeblog.post import Post
from makeblog.config import readconfig, writedefaultconfig
from makeblog.server import Server
from makeblog.plugins import load_plugins
from sys import exit

# Parse cmdline args
parse_args()
# Read configuration
config = readconfig()
# Load all User created Plugins
load_plugins('plugins')

# Verify configuration exists and --init is not passed:
if not config and not options.init:
    exit('Sorry, no configuration file found.')

if options.title:
    b = Blog(config)
    p = Post(b)
    print(p.new(options.title, options.draft))
    p.save()
elif options.update:
    b = Blog(config)
    p = Post(b)
    p.load(options.update)
    p.update()
    p.save()
elif options.build:
    b = Blog(config)
    b.build(options.draft)
elif options.serve:
    s = Server()
    s.serve()
elif options.init:
    if not writedefaultconfig():
        print("You should edit config.json.")
