#!/usr/bin/python
# makeblog - A simple offline Blog.
# Copyright (C) 2013 Stefan J. Betz <info@stefan-betz.net>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from makeblog.tools import options
from makeblog.blog import Blog
from makeblog.post import Post
from makeblog.config import DEFAULT_CONFIG
from makeblog.server import Server
from os import access, F_OK, makedirs
from os.path import exists
import json

if options.title:
    b = Blog()
    p = Post(b)
    p.new(options.title)
    p.save()
elif options.update:
    b = Blog()
    p = Post(b)
    p.load(options.update)
    p.update()
    p.save()
elif options.build:
    b = Blog()
    b.build()
elif options.serve:
    s = Server()
    s.serve()
elif options.init:
    for directory in ('src','posts','drafts'):
        if not exists(directory):
            makedirs(directory)
    if not access('config.json', F_OK):
        with open('config.json','w') as f:
            json.dump(DEFAULT_CONFIG,f,indent=1,ensure_ascii=False)
        print("You should edit config.json.")
